"""Initial Database Revision

Revision ID: 0cdb2428566d
Revises: 
Create Date: 2020-04-14 07:38:38.051868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdb2428566d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_artist_name'), 'artist', ['artist_name'], unique=True)
    op.create_table('configuration',
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('recording',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_name', sa.String(length=80), nullable=True),
    sa.Column('label', sa.String(length=20), nullable=True),
    sa.Column('label_number', sa.String(length=20), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('cover', sa.Boolean(), nullable=True),
    sa.Column('word', sa.Boolean(), nullable=True),
    sa.Column('count_cassette', sa.Integer(), nullable=True),
    sa.Column('count_lp', sa.Integer(), nullable=True),
    sa.Column('count_45', sa.Integer(), nullable=True),
    sa.Column('count_78', sa.Integer(), nullable=True),
    sa.Column('count_cd', sa.Integer(), nullable=True),
    sa.Column('count_digital', sa.Integer(), nullable=True),
    sa.Column('count_copy_cassette', sa.Integer(), nullable=True),
    sa.Column('count_copy_cd', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recording_record_name'), 'recording', ['record_name'], unique=False)
    op.create_table('song',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('song_name', sa.String(length=35), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['recording.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    op.drop_index(op.f('ix_recording_record_name'), table_name='recording')
    op.drop_table('recording')
    op.drop_table('configuration')
    op.drop_index(op.f('ix_artist_artist_name'), table_name='artist')
    op.drop_table('artist')
    # ### end Alembic commands ###
