"""remove relationships

Revision ID: 2fd8ab2eeb1a
Revises: 8ce701ee579b
Create Date: 2019-03-10 07:06:53.724542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd8ab2eeb1a'
down_revision = '8ce701ee579b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artis')
    op.drop_table('songs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('Song_ID', sa.TEXT(), nullable=True),
    sa.Column('Song_Name', sa.TEXT(), nullable=True),
    sa.Column('Record_ID', sa.TEXT(), nullable=True)
    )
    op.create_table('artis',
    sa.Column('Artist_ID', sa.TEXT(), nullable=True),
    sa.Column('Artist_Name', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
